name: bFundamentals
main: uk.codingbadgers.bFundamentals.bFundamentals
version: 1.0
authors: [n3wton, thefish97]
description: Fundamental plugins root plugin

commands:
    bFundamentals:
        description: Main command for the plugin
        usage: /<command> 